### ISSUE TITLE
Support YouTube videos

### ISSUE THREAD

**Issue by aaweb** [AdaRoseCannon/aframe-htmlmesh#1]
Hey Ada. Thanks for the great work with all of your repos. Your aframe-xr-boilerplate scene is brilliant!

I was having a quick play with this to see if it is possible to render videos with this method by using a simple `iframe` or `video` tag. So far it's not displaying anything. I wonder if you had tried it?

There seems to be a way using THREE.js as shown here:
https://codepen.io/asjas/pen/pWawPm

**Comment by AdaRoseCannon** [comment]
This is impossible, it's not actually displaying real HTML, it's redrawing it using canvas commands. So video wouldn't work. 

For videos take a look at using WebXR layers https://aframe.io/docs/1.3.0/components/layer.html

**Comment by AdaRoseCannon** [comment]
For the record layers can't support youtube videos either because they can't access the content of frames. 

There are future proposed APIs which may help there.
