### ISSUE TITLE
Add support for images

### ISSUE THREAD

**Issue by vincentfretin** [AdaRoseCannon/aframe-htmlmesh#13]
Search for `ctx.drawImage` in https://github.com/niklasvh/html2canvas/blob/6521a487d78172f7179f7c973c1a3af40eb92009/src/render/canvas/canvas-renderer.ts for an example how this can be implemented.

**Comment by AdaRoseCannon** [comment]
This isn't something I super want to encourage, images would be best handled separately as textures on meshes.

**Comment by vincentfretin** [comment]
I don't have an immediate need for this, I was discussing with someone about it.
I'll surely avoid it if I can, especially if I'm using HTMLMesh for the interactive part. If there is no interaction, it's rendered only once so it shouldn't matter much for perf. Is it really an issue for perf, rendering an image on a canvas? I'm not sure.
But it may make sense for some cases if you have some text, an image and some other text, for content that can be dynamic and not written by you so you don't know in advance the height of the various texts and you absolutely want the same background color for all of it, just an example.

**Comment by vincentfretin** [comment]
three r151 added image support to HTMLMesh.js but it's wrong, all images render at the top left.
The following code works great:
https://github.com/mrdoob/three.js/pull/25660/files#r1175427534
