### ISSUE TITLE
When i appendChild htmlmesh on other tag,it can't work well

### ISSUE THREAD

**Issue by twice7713** [AdaRoseCannon/aframe-htmlmesh#17]
when i used this newTransform.appendChild(htmlmesh) that can't work

**Comment by vincentfretin** [comment]
What do you mean by that? What is newTransform and htmlmesh here? Can you please provide an example on glitch of what you're trying to do?

**Comment by twice7713** [comment]
![1](https://github.com/AdaRoseCannon/aframe-htmlmesh/assets/57941062/59c5d68d-446f-4592-9414-0b31be087609)
![2](https://github.com/AdaRoseCannon/aframe-htmlmesh/assets/57941062/dc11a2e9-4499-44d8-b895-74fd547e2cf9)

**Comment by vincentfretin** [comment]
Ok, and what's your issue? You don't see the htmlmesh? Probably an error in your this.transformSet.
I added an htmlmesh to my cameraRig a few weeks ago to have a chat with answers visible in front of me, that works.

**Comment by vincentfretin** [comment]
I guess it shows now if you created #18 so I can close.
